samples: config/samples.tsv

references:
  # Bowtie2 index prefix, without the .1.bt2 suffix.
  bostaurus_index: /archive/extra/daniel.remondini2/bioinf_db/databases/bostaurus_bosTau9_bowtie2/bosTau9

containers:
  kneaddata: /archive/extra/daniel.remondini2/bioinf_db/containers/kneaddata/0.12.4/kneaddata_0.12.4.sif
